var simplemde = new SimpleMDE({ element: document.getElementById("simplemde") });

const help1 = document.getElementById("subcategory-help");
const help2 = document.getElementById("subcategory-help2");
const tooltip = document.querySelector('#tooltip');
const autoGenBox = document.getElementById("flexSwitchCheckChecked");
const topicDiv = document.getElementById("topicDiv");
if(help1!=null){changeTooltip();}
if(help2!=null){createPopperHelp2();}

function changeTooltip(){
    let select = document.getElementById("category-select");
    let category = select.options[select.selectedIndex].value;
    
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        let description = this.responseText;
        tooltip.innerHTML = description;
        const popperInstance = Popper.createPopper(help1,tooltip,{
            placement: 'right-start',
            modifiers: [
                {
                  name: 'offset',
                  options: {
                    offset: [0, 8],
                  },
                },
              ],
        });
        popperInstance.update();
    }
    };
    xmlhttp.open("GET","function/subcategoryToolTip.php?subid="+category,true);
    xmlhttp.send();
}
function createPopperHelp2(){
    const popperInstance = Popper.createPopper(help2,tooltip,{
        placement: 'right-start',
        modifiers: [
            {
              name: 'offset',
              options: {
                offset: [0, 8],
              },
            },
          ],
    });
    popperInstance.update();
}

function show() {
    tooltip.setAttribute('data-show', '');
  
    // We need to tell Popper to update the tooltip position
    // after we show the tooltip, otherwise it will be incorrect
    
  }
  
  function hide() {
    tooltip.removeAttribute('data-show');
  }
  
  const showEvents = ['mouseenter', 'focus'];
  const hideEvents = ['mouseleave', 'blur'];
  
  showEvents.forEach((event) => {
    if(help1!=null){help1.addEventListener(event, show);}
    if(help2!=null){help2.addEventListener(event, show);}
    
    
  });
  
  hideEvents.forEach((event) => {
    if(help1!=null){help1.addEventListener(event, hide);}
    if(help2!=null){help2.addEventListener(event, hide);}
    
    
  });


//(autoGenBox.checked)
function boxClicked(){
    topicDiv.classList.toggle("hidden");
    //let checkbox = document.getElementById("flexSwitchCheckChecked");
    //console.log(checkbox.checked);
}
const topicsinput = document.getElementById("topic-input");
topicsinput.addEventListener("keypress",function(event){
    if (event.key === "Enter") {
        event.preventDefault();
        addTopic();
    }   
});
function addTopic(){
    value = topicsinput.value.toLowerCase().replace(/[^a-z0-9 -]/g, '');;
    value.trim();
    if(value!=""){
        addTopicVal(value);
        document.getElementById("topic-input").value ="";
    }
    
}
//
let topicsSet = new Set();
function addTopicVal(value){
    topicsSet.add(value);
    renderTopics();
}

function renderTopics(){
    topics = document.getElementById("topics-display");
    str ="";
    topicsSet.forEach(element=>{
        str += "<span class='badge rounded-pill bg-light' onclick='removeTopic(this.innerText)'>"+element+"</span>";
    });
    topics.innerHTML = str;
}
function generateRandomTopic(){
    let topic = allTopic[Math.floor(Math.random() * allTopic.length)];
    addTopicVal(topic);
}
function removeTopic(value){
    topicsSet.delete(value);
    renderTopics();
}
function getTopics(){
    topics = document.getElementById("topics-display");
}
function generateTopics(){
    let hidden = document.getElementById('hidetopic');
    let val = JSON.stringify([...topicsSet]);
    hidden.value = val;
    return val;
}

function test(){
    let topics = generateTopics();
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        console.log(this.responseText);
    }
    };
    xmlhttp.open("GET","function/test.php?topics="+topics,true);
    xmlhttp.send();
}

const allTopic = [
    "academia",
    "acarology",
    "accounting",
    "acrobatics",
    "acting",
    "advertising",
    "aerial freestyle",
    "aerodynamics",
    "aeronautics",
    "aerospace",
    "agriculture",
    "alchemy",
    "algebra",
    "algebraic geometry",
    "algebraic topology",
    "alpine skiing",
    "alternative medicine",
    "analytic number theory",
    "anarchism",
    "anatomy",
    "andrology",
    "angelology",
    "anime",
    "anthropology",
    "applied sciences",
    "arachnology",
    "archaeology",
    "archeology",
    "archery",
    "architecture",
    "areology",
    "arithmetic",
    "army",
    "art",
    "art history",
    "arts",
    "astrocartography",
    "astrogeology",
    "astrology",
    "astronautics",
    "astronomy",
    "astrophysics",
    "athletics",
    "audio",
    "authorship",
    "automobile",
    "automotive",
    "aviation",
    "backgammon",
    "bacteriology",
    "baking",
    "ball games",
    "ballistics",
    "ballooning",
    "banking",
    "baseball",
    "basketball",
    "beekeeping",
    "beer",
    "behavior",
    "behavioral sciences",
    "beverages",
    "biblical",
    "bibliography",
    "billiards",
    "bingo",
    "biochemistry",
    "biogeography",
    "bioinformatics",
    "biology",
    "biotechnology",
    "birdwatching",
    "blackjack",
    "blogging",
    "board games",
    "body",
    "bodybuilding",
    "bone",
    "bookbinding",
    "botany",
    "bowling",
    "bowmaking",
    "boxing",
    "brewing",
    "brick making",
    "bridge",
    "broadcasting",
    "bryology",
    "bullfighting",
    "business",
    "calculus",
    "calligraphy",
    "campanology",
    "capitalism",
    "card games",
    "cardiology",
    "cards",
    "carpentry",
    "cartography",
    "cartomancy",
    "category theory",
    "caving",
    "cellular automata",
    "ceramics",
    "cheerleading",
    "chemistry",
    "chess",
    "chromatography",
    "chronology",
    "cigars",
    "cinematography",
    "circus",
    "cities",
    "city",
    "civil engineering",
    "classical studies",
    "climate",
    "climatology",
    "climbing",
    "clinical psychology",
    "clothing",
    "codicology",
    "colleges",
    "color",
    "colorimetry",
    "colour",
    "combinatorics",
    "comedy",
    "comics",
    "commerce",
    "commercial",
    "communication",
    "communications",
    "communism",
    "complex analysis",
    "computational",
    "computer",
    "computer games",
    "computer graphics",
    "computer hardware",
    "computer languages",
    "computer sciences",
    "computer software",
    "computing",
    "computing theory",
    "conchology",
    "conservation",
    "construction",
    "cooking",
    "copyright",
    "cosmetics",
    "cosmology",
    "countries",
    "country",
    "country dancing",
    "court",
    "crafts",
    "creationism",
    "cricket",
    "criminology",
    "crocheting",
    "cryptocurrencies",
    "cryptocurrency",
    "cryptography",
    "cryptozoology",
    "crystallography",
    "cuisine",
    "curling",
    "cycling",
    "cytology",
    "dance",
    "dancing",
    "darts",
    "databases",
    "demographics",
    "demography",
    "demonology",
    "demoscene",
    "dentistry",
    "dermatology",
    "design",
    "dialectology",
    "dice",
    "diplomacy",
    "diving",
    "dogs",
    "dominoes",
    "drafting",
    "drama",
    "dramaturgy",
    "dressage",
    "dressmaking",
    "drugs",
    "duration",
    "dyeing",
    "ecclesiastical",
    "ecology",
    "economic liberalism",
    "economics",
    "editing",
    "education",
    "electrical",
    "electrical engineering",
    "electricity",
    "electrochemistry",
    "electromagnetism",
    "electronics",
    "electronics manufacturing",
    "embryology",
    "emergency medicine",
    "encryption",
    "endocrinology",
    "energy",
    "engineering",
    "engraving",
    "entertainment",
    "entertainment industry",
    "entomology",
    "epidemiology",
    "epigraphy",
    "epistemology",
    "equestrianism",
    "equitation",
    "espionage",
    "ethics",
    "ethnography",
    "ethnology",
    "etymology",
    "exercise",
    "existentialism",
    "falconry",
    "fantasy",
    "farriery",
    "fascism",
    "fashion",
    "fasteners",
    "feminism",
    "fencing",
    "feudalism",
    "fiction",
    "film",
    "finance",
    "finances",
    "financial",
    "firearms",
    "firefighting",
    "fish",
    "fisheries",
    "fishing",
    "fluid dynamics",
    "fluids",
    "folklore",
    "food",
    "football",
    "forestry",
    "fortification",
    "fortifications",
    "freemasonry",
    "furniture",
    "gambling",
    "game of Go",
    "game theory",
    "games",
    "gaming",
    "gastroenterology",
    "gem cutting",
    "gemmology",
    "gemology",
    "genetics",
    "geographical region",
    "geography",
    "geology",
    "geometry",
    "geomorphology",
    "geopolitics",
    "gerontology",
    "glaciology",
    "glassblowing",
    "glassmaking",
    "golf",
    "government",
    "graffiti",
    "grammar",
    "graph theory",
    "graphic design",
    "graphical user interface",
    "group theory",
    "guitar",
    "gymnastics",
    "gynaecology",
    "hairdressing",
    "handball",
    "handbells",
    "hawking",
    "heading",
    "health",
    "healthcare",
    "hematology",
    "heraldry",
    "herpetology",
    "higher education",
    "hinduism",
    "hip hop",
    "histology",
    "histopathology",
    "historical demography",
    "historical ethnography",
    "historical geography",
    "historiography",
    "history",
    "hobbies",
    "homeopathy",
    "horology",
    "horse racing",
    "horseracing",
    "horses",
    "horticulture",
    "human sciences",
    "hunting",
    "hydraulics",
    "hydrodynamics",
    "hydrography",
    "hydrology",
    "ice hockey",
    "ichthyology",
    "iconography",
    "ideology",
    "illness",
    "immunochemistry",
    "immunology",
    "in technical contexts",
    "informatics",
    "information",
    "information science",
    "information technology",
    "information theory",
    "inorganic chemistry",
    "insects",
    "insurance",
    "intellectual property",
    "investment",
    "ironworking",
    "jewellery",
    "jewelry",
    "journalism",
    "judo",
    "juggling",
    "knitting",
    "lacrosse",
    "language",
    "law",
    "law enforcement",
    "lepidopterology",
    "letterpress typography",
    "lexicography",
    "lichenology",
    "lifestyle",
    "limnology",
    "linear algebra",
    "linguistic",
    "linguistic morphology",
    "linguistics",
    "literature",
    "lithography",
    "location",
    "logic",
    "lubricants",
    "lutherie",
    "machining",
    "mahjong",
    "mail",
    "malacology",
    "mammalogy",
    "mammology",
    "management",
    "manga",
    "manner",
    "manosphere",
    "manufacturing",
    "maritime",
    "marketing",
    "martial arts",
    "masonry",
    "mathematical analysis",
    "mathematics",
    "measure theory",
    "meat",
    "meats",
    "mechanical",
    "mechanical engineering",
    "mechanics",
    "media",
    "medicine",
    "metallurgy",
    "metalworking",
    "meteorology",
    "metrology",
    "microbiology",
    "microeconomics",
    "military",
    "mineralogy",
    "mineralology",
    "mining",
    "mobile telephony",
    "modelling",
    "monarchy",
    "money",
    "morphology",
    "motor racing",
    "motorcycling",
    "mountaineering",
    "music",
    "musicology",
    "mycology",
    "mysticism",
    "mythology",
    "nanotechnology",
    "narratology",
    "natural sciences",
    "naturism",
    "nautical",
    "naval",
    "navy",
    "nematology",
    "nephrology",
    "netball",
    "networking",
    "neuroanatomy",
    "neurobiology",
    "neurology",
    "neurophysiology",
    "neuroscience",
    "neurotoxicology",
    "newspapers",
    "nobility",
    "number theory",
    "numismatics",
    "obstetrics",
    "occult",
    "occultism",
    "oceanography",
    "odontology",
    "oenology",
    "officialese",
    "oncology",
    "ontology",
    "ophthalmology",
    "optics",
    "order theory",
    "organic chemistry",
    "organization",
    "ornithology",
    "orthography",
    "paganism",
    "paintball",
    "palaeography",
    "palentology",
    "paleoanthropology",
    "paleobiology",
    "paleogeography",
    "paleography",
    "paleontology",
    "palynology",
    "papercraft",
    "papermaking",
    "parachuting",
    "parapsychology",
    "parasitology",
    "parliamentary procedure",
    "patent law",
    "pathology",
    "pedology",
    "performing arts",
    "pesäpallo",
    "petrochemistry",
    "petrography",
    "petroleum",
    "petrology",
    "pets",
    "pharmaceuticals",
    "pharmacology",
    "phenomenology",
    "philately",
    "philosophy",
    "phonetics",
    "phonology",
    "photography",
    "phrenology",
    "phycology",
    "physical sciences",
    "physics",
    "physiology",
    "phytopathology",
    "piledriving",
    "planetology",
    "planets",
    "planktology",
    "plumbing",
    "pneumology",
    "pocket billiards",
    "poetry",
    "poker",
    "police",
    "political science",
    "politics",
    "pool",
    "pragmatics",
    "printing",
    "printing technology",
    "probability",
    "probability theory",
    "professional wrestling",
    "programming",
    "property",
    "prosody",
    "prostitution",
    "pseudoscience",
    "psychiatry",
    "psychoanalysis",
    "psycholinguistics",
    "psychology",
    "psychopathology",
    "publishing",
    "pulmonology",
    "quantum field theory",
    "quarrying",
    "quilting",
    "racing",
    "racquet sports",
    "radio",
    "radio communications",
    "radio technics",
    "radio technology",
    "radiography",
    "radiology",
    "rail transport",
    "railways",
    "real estate",
    "region",
    "regionalism",
    "religion",
    "retail",
    "retailing",
    "road",
    "robotics",
    "roguelikes",
    "role playing games",
    "roofing",
    "ropemaking",
    "rowing",
    "rugby",
    "sailing",
    "sailmaking",
    "scholarly",
    "science",
    "science fiction",
    "sciences",
    "scientific",
    "scriptwriting",
    "seafood",
    "seasons",
    "seduction community",
    "seismology",
    "semantics",
    "semiotics",
    "set theory",
    "sewage treatment",
    "sewing",
    "sheepdog trials",
    "shipbuilding",
    "shipping",
    "shogi",
    "signal processing",
    "skateboarding",
    "skating",
    "skiing",
    "skydiving",
    "smithwork",
    "smoking",
    "snooker",
    "snowboarding",
    "soccer",
    "social science",
    "social sciences",
    "socialism",
    "sociobiology",
    "sociolinguistics",
    "sociology",
    "sociopolitics",
    "softball",
    "software",
    "software compilation",
    "space science",
    "space sciences",
    "speech pathology",
    "speech therapy",
    "spinning",
    "spiritualism",
    "sports",
    "squash",
    "state",
    "states",
    "statistics",
    "stock exchange",
    "stock market",
    "stock ticker symbol",
    "stone",
    "stratigraphy",
    "sugar making",
    "sumo",
    "surfing",
    "surgery",
    "surveying",
    "swimming",
    "syntax",
    "systems theory",
    "talking",
    "tarot",
    "taxation",
    "taxonomy",
    "technical",
    "technology",
    "telecommunications",
    "telegraphy",
    "telephone",
    "telephony",
    "television",
    "temperature",
    "temporal location",
    "tennis",
    "teratology",
    "textiles",
    "textual criticism",
    "theater",
    "theology",
    "thermodynamics",
    "time",
    "tin plate manufacture",
    "tools",
    "topography",
    "topology",
    "tourism",
    "toxicology",
    "trading",
    "traffic",
    "trains",
    "translation studies",
    "transport",
    "traumatology",
    "travel",
    "travel industry",
    "trigonometry",
    "typography",
    "ufology",
    "underwater diving",
    "units of measure",
    "uranography",
    "urbanism",
    "urology",
    "veganism",
    "vegetable",
    "vehicles",
    "veterinary",
    "veterinary pathology",
    "vexillology",
    "video games",
    "videography",
    "virology",
    "visual art",
    "visual arts",
    "volcanology",
    "volleyball",
    "wagonmaking",
    "war",
    "weapon",
    "weaponry",
    "weather",
    "weaving",
    "web design",
    "weightlifting",
    "wine",
    "wireless telegraphy",
    "woodworking",
    "wrestling",
    "writing",
    "zoology",
    "zootomy"
  ]

  /*
  using 
  let all = document.querySelectorAll(":not(ul.breadcrumb)>li");
let arr = [];
for(let i = 0;i<all.length;i++){
  arr.push(all[i].innerText.replace
    in 
https://kaikki.org/dictionary/English/topics.html
   */